In [1]:
from conversion.c3d_utils.utils import convert_ez3d_to_eurobench

In [2]:
c3d_filename = '/Users/jorge/Downloads/subject_02_cond_vn_run_04.c3d'

In [3]:
df_data, df_analogs, dict_events, dict_params, fs_data, fs_analog = convert_ez3d_to_eurobench(
            c3d_filename,
            debug=False,
            b_cat_analog_description=False,
            b_cat_analog_unit=False,
        )

### Data

In [4]:
df_data

,PELO_x,PELO_y,PELO_z,PELA_x,PELA_y,PELA_z,PELL_x,PELL_y,PELL_z,PELP_x,...,RTHI_x,RTHI_y,RTHI_z,CentreOfMass_x,CentreOfMass_y,CentreOfMass_z,CentreOfMassFloor_x,CentreOfMassFloor_y,CentreOfMassFloor_z,time
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.01
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.02
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.03
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2350,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.50
2351,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.51
2352,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.52
2353,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.53
2354,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.54

In [9]:
# Pretty print list of columns in the data file
print(df_data.columns.values)

['PELO_x' 'PELO_y' 'PELO_z' 'PELA_x' 'PELA_y' 'PELA_z' 'PELL_x' 'PELL_y'
 'PELL_z' 'PELP_x' 'PELP_y' 'PELP_z' 'LFEO_x' 'LFEO_y' 'LFEO_z' 'LFEA_x'
 'LFEA_y' 'LFEA_z' 'LFEL_x' 'LFEL_y' 'LFEL_z' 'LFEP_x' 'LFEP_y' 'LFEP_z'
 'LTIO_x' 'LTIO_y' 'LTIO_z' 'LTIA_x' 'LTIA_y' 'LTIA_z' 'LTIL_x' 'LTIL_y'
 'LTIL_z' 'LTIP_x' 'LTIP_y' 'LTIP_z' 'LFOO_x' 'LFOO_y' 'LFOO_z' 'LFOA_x'
 'LFOA_y' 'LFOA_z' 'LFOL_x' 'LFOL_y' 'LFOL_z' 'LFOP_x' 'LFOP_y' 'LFOP_z'
 'RFEO_x' 'RFEO_y' 'RFEO_z' 'RFEA_x' 'RFEA_y' 'RFEA_z' 'RFEL_x' 'RFEL_y'
 'RFEL_z' 'RFEP_x' 'RFEP_y' 'RFEP_z' 'RTIO_x' 'RTIO_y' 'RTIO_z' 'RTIA_x'
 'RTIA_y' 'RTIA_z' 'RTIL_x' 'RTIL_y' 'RTIL_z' 'RTIP_x' 'RTIP_y' 'RTIP_z'
 'RFOO_x' 'RFOO_y' 'RFOO_z' 'RFOA_x' 'RFOA_y' 'RFOA_z' 'RFOL_x' 'RFOL_y'
 'RFOL_z' 'RFOP_x' 'RFOP_y' 'RFOP_z' 'LTOO_x' 'LTOO_y' 'LTOO_z' 'LTOA_x'
 'LTOA_y' 'LTOA_z' 'LTOL_x' 'LTOL_y' 'LTOL_z' 'LTOP_x' 'LTOP_y' 'LTOP_z'
 'RTOO_x' 'RTOO_y' 'RTOO_z' 'RTOA_x' 'RTOA_y' 'RTOA_z' 'RTOL_x' 'RTOL_y'
 'RTOL_z' 'RTOP_x' 'RTOP_y' 'RTOP_z' 'HEDO_x' 'HEDO_y' 'HEDO_z' 'HEDA_x'
 'HEDA_y' 'HEDA_z' 'HEDL_x' 'HEDL_y' 'HEDL_z' 'HEDP_x' 'HEDP_y' 'HEDP_z'
 'LCLO_x' 'LCLO_y' 'LCLO_z' 'LCLA_x' 'LCLA_y' 'LCLA_z' 'LCLL_x' 'LCLL_y'
 'LCLL_z' 'LCLP_x' 'LCLP_y' 'LCLP_z' 'RCLO_x' 'RCLO_y' 'RCLO_z' 'RCLA_x'
 'RCLA_y' 'RCLA_z' 'RCLL_x' 'RCLL_y' 'RCLL_z' 'RCLP_x' 'RCLP_y' 'RCLP_z'
 'TRXO_x' 'TRXO_y' 'TRXO_z' 'TRXA_x' 'TRXA_y' 'TRXA_z' 'TRXL_x' 'TRXL_y'
 'TRXL_z' 'TRXP_x' 'TRXP_y' 'TRXP_z' 'LHUO_x' 'LHUO_y' 'LHUO_z' 'LHUA_x'
 'LHUA_y' 'LHUA_z' 'LHUL_x' 'LHUL_y' 'LHUL_z' 'LHUP_x' 'LHUP_y' 'LHUP_z'
 'LRAO_x' 'LRAO_y' 'LRAO_z' 'LRAA_x' 'LRAA_y' 'LRAA_z' 'LRAL_x' 'LRAL_y'
 'LRAL_z' 'LRAP_x' 'LRAP_y' 'LRAP_z' 'LHNO_x' 'LHNO_y' 'LHNO_z' 'LHNA_x'
 'LHNA_y' 'LHNA_z' 'LHNL_x' 'LHNL_y' 'LHNL_z' 'LHNP_x' 'LHNP_y' 'LHNP_z'
 'RHUO_x' 'RHUO_y' 'RHUO_z' 'RHUA_x' 'RHUA_y' 'RHUA_z' 'RHUL_x' 'RHUL_y'
 'RHUL_z' 'RHUP_x' 'RHUP_y' 'RHUP_z' 'RRAO_x' 'RRAO_y' 'RRAO_z' 'RRAA_x'
 'RRAA_y' 'RRAA_z' 'RRAL_x' 'RRAL_y' 'RRAL_z' 'RRAP_x' 'RRAP_y' 'RRAP_z'
 'RHNO_x' 'RHNO_y' 'RHNO_z' 'RHNA_x' 'RHNA_y' 'RHNA_z' 'RHNL_x' 'RHNL_y'
 'RHNL_z' 'RHNP_x' 'RHNP_y' 'RHNP_z' 'RBHD_x' 'RBHD_y' 'RBHD_z' 'LSHO_x'
 'LSHO_y' 'LSHO_z' 'RSHO_x' 'RSHO_y' 'RSHO_z' 'RTIB_x' 'RTIB_y' 'RTIB_z'
 'T10_x' 'T10_y' 'T10_z' 'RWRB_x' 'RWRB_y' 'RWRB_z' 'RTOE_x' 'RTOE_y'
 'RTOE_z' 'LBHD_x' 'LBHD_y' 'LBHD_z' 'RANK_x' 'RANK_y' 'RANK_z' 'RMTF_x'
 'RMTF_y' 'RMTF_z' 'RFRM_x' 'RFRM_y' 'RFRM_z' 'RPSI_x' 'RPSI_y' 'RPSI_z'
 'RKNE_x' 'RKNE_y' 'RKNE_z' 'LMedANK_x' 'LMedANK_y' 'LMedANK_z' 'LPSI_x'
 'LPSI_y' 'LPSI_z' 'RTIP_NIM_x' 'RTIP_NIM_y' 'RTIP_NIM_z' 'RELB_x'
 'RELB_y' 'RELB_z' 'LFRM_x' 'LFRM_y' 'LFRM_z' 'RWRA_x' 'RWRA_y' 'RWRA_z'
 'LTIP_NIM_x' 'LTIP_NIM_y' 'LTIP_NIM_z' 'LMTF_x' 'LMTF_y' 'LMTF_z'
 'Addi_R_ULeg_x' 'Addi_R_ULeg_y' 'Addi_R_ULeg_z' 'LKNE_x' 'LKNE_y'
 'LKNE_z' 'RFIN_x' 'RFIN_y' 'RFIN_z' 'LFHD_x' 'LFHD_y' 'LFHD_z' 'LWRA_x'
 'LWRA_y' 'LWRA_z' 'LTHI_x' 'LTHI_y' 'LTHI_z' 'RMedANK_x' 'RMedANK_y'
 'RMedANK_z' 'RFHD_x' 'RFHD_y' 'RFHD_z' 'LELB_x' 'LELB_y' 'LELB_z'
 'LTRO_x' 'LTRO_y' 'LTRO_z' 'LWRB_x' 'LWRB_y' 'LWRB_z' 'RTRO_x' 'RTRO_y'
 'RTRO_z' 'LUPA_x' 'LUPA_y' 'LUPA_z' 'LTOE_x' 'LTOE_y' 'LTOE_z' 'LFIN_x'
 'LFIN_y' 'LFIN_z' 'Addi_L_ULeg_x' 'Addi_L_ULeg_y' 'Addi_L_ULeg_z'
 'LASI_x' 'LASI_y' 'LASI_z' 'RHEE_x' 'RHEE_y' 'RHEE_z' 'LTIB_x' 'LTIB_y'
 'LTIB_z' 'CLAV_x' 'CLAV_y' 'CLAV_z' 'RASI_x' 'RASI_y' 'RASI_z' 'LHEE_x'
 'LHEE_y' 'LHEE_z' 'STRN_x' 'STRN_y' 'STRN_z' 'LANK_x' 'LANK_y' 'LANK_z'
 'C7_x' 'C7_y' 'C7_z' 'RBAK_x' 'RBAK_y' 'RBAK_z' 'RUPA_x' 'RUPA_y'
 'RUPA_z' '*124_x' '*124_y' '*124_z' '*125_x' '*125_y' '*125_z' '*126_x'
 '*126_y' '*126_z' '*127_x' '*127_y' '*127_z' '*128_x' '*128_y' '*128_z'
 '*129_x' '*129_y' '*129_z' '*130_x' '*130_y' '*130_z' '*131_x' '*131_y'
 '*131_z' '*132_x' '*132_y' '*132_z' '*133_x' '*133_y' '*133_z' '*134_x'
 '*134_y' '*134_z' '*135_x' '*135_y' '*135_z' '*136_x' '*136_y' '*136_z'
 '*137_x' '*137_y' '*137_z' '*138_x' '*138_y' '*138_z' '*139_x' '*139_y'
 '*139_z' '*140_x' '*140_y' '*140_z' '*141_x' '*141_y' '*141_z' '*142_x'
 '*142_y' '*142_z' '*143_x' '*143_y' '*143_z' '*144_x' '*144_y' '*144_z'
 '*145_x' '*145_y' '*145_z' '*146_x' '*146_y' '*146_z' '*147_x' '*147_y'
 '*147_z' '*148_x' '*148_y' '*148_z' '*149_x' '*149_y' '*149_z' '*150_x'
 '*150_y' '*150_z' '*151_x' '*151_y' '*151_z' '*152_x' '*152_y' '*152_z'
 '*153_x' '*153_y' '*153_z' '*154_x' '*154_y' '*154_z' '*155_x' '*155_y'
 '*155_z' '*156_x' '*156_y' '*156_z' '*157_x' '*157_y' '*157_z' '*158_x'
 '*158_y' '*158_z' '*159_x' '*159_y' '*159_z' '*160_x' '*160_y' '*160_z'
 '*161_x' '*161_y' '*161_z' '*162_x' '*162_y' '*162_z' 'LHipAngles_x'
 'LHipAngles_y' 'LHipAngles_z' 'LKneeAngles_x' 'LKneeAngles_y'
 'LKneeAngles_z' 'LAbsAnkleAngle_x' 'LAbsAnkleAngle_y' 'LAbsAnkleAngle_z'
 'LAnkleAngles_x' 'LAnkleAngles_y' 'LAnkleAngles_z' 'RHipAngles_x'
 'RHipAngles_y' 'RHipAngles_z' 'RKneeAngles_x' 'RKneeAngles_y'
 'RKneeAngles_z' 'RAnkleAngles_x' 'RAnkleAngles_y' 'RAnkleAngles_z'
 'RAbsAnkleAngle_x' 'RAbsAnkleAngle_y' 'RAbsAnkleAngle_z'
 'LPelvisAngles_x' 'LPelvisAngles_y' 'LPelvisAngles_z' 'RPelvisAngles_x'
 'RPelvisAngles_y' 'RPelvisAngles_z' 'LFootProgressAngles_x'
 'LFootProgressAngles_y' 'LFootProgressAngles_z' 'RFootProgressAngles_x'
 'RFootProgressAngles_y' 'RFootProgressAngles_z' 'RNeckAngles_x'
 'RNeckAngles_y' 'RNeckAngles_z' 'LNeckAngles_x' 'LNeckAngles_y'
 'LNeckAngles_z' 'RSpineAngles_x' 'RSpineAngles_y' 'RSpineAngles_z'
 'LSpineAngles_x' 'LSpineAngles_y' 'LSpineAngles_z' 'LShoulderAngles_x'
 'LShoulderAngles_y' 'LShoulderAngles_z' 'LElbowAngles_x' 'LElbowAngles_y'
 'LElbowAngles_z' 'LWristAngles_x' 'LWristAngles_y' 'LWristAngles_z'
 'RShoulderAngles_x' 'RShoulderAngles_y' 'RShoulderAngles_z'
 'RElbowAngles_x' 'RElbowAngles_y' 'RElbowAngles_z' 'RWristAngles_x'
 'RWristAngles_y' 'RWristAngles_z' 'RThoraxAngles_x' 'RThoraxAngles_y'
 'RThoraxAngles_z' 'LThoraxAngles_x' 'LThoraxAngles_y' 'LThoraxAngles_z'
 'RHeadAngles_x' 'RHeadAngles_y' 'RHeadAngles_z' 'LHeadAngles_x'
 'LHeadAngles_y' 'LHeadAngles_z' 'LHipPower_x' 'LHipPower_y' 'LHipPower_z'
 'LKneePower_x' 'LKneePower_y' 'LKneePower_z' 'LAnklePower_x'
 'LAnklePower_y' 'LAnklePower_z' 'RHipPower_x' 'RHipPower_y' 'RHipPower_z'
 'RKneePower_x' 'RKneePower_y' 'RKneePower_z' 'RAnklePower_x'
 'RAnklePower_y' 'RAnklePower_z' 'LWaistPower_x' 'LWaistPower_y'
 'LWaistPower_z' 'RWaistPower_x' 'RWaistPower_y' 'RWaistPower_z'
 'LNeckPower_x' 'LNeckPower_y' 'LNeckPower_z' 'RNeckPower_x'
 'RNeckPower_y' 'RNeckPower_z' 'LShoulderPower_x' 'LShoulderPower_y'
 'LShoulderPower_z' 'RShoulderPower_x' 'RShoulderPower_y'
 'RShoulderPower_z' 'LElbowPower_x' 'LElbowPower_y' 'LElbowPower_z'
 'RElbowPower_x' 'RElbowPower_y' 'RElbowPower_z' 'LWristPower_x'
 'LWristPower_y' 'LWristPower_z' 'RWristPower_x' 'RWristPower_y'
 'RWristPower_z' 'RGroundReactionForce_x' 'RGroundReactionForce_y'
 'RGroundReactionForce_z' 'RNormalisedGRF_x' 'RNormalisedGRF_y'
 'RNormalisedGRF_z' 'LAnkleForce_x' 'LAnkleForce_y' 'LAnkleForce_z'
 'RAnkleForce_x' 'RAnkleForce_y' 'RAnkleForce_z' 'RKneeForce_x'
 'RKneeForce_y' 'RKneeForce_z' 'LKneeForce_x' 'LKneeForce_y'
 'LKneeForce_z' 'RHipForce_x' 'RHipForce_y' 'RHipForce_z' 'LHipForce_x'
 'LHipForce_y' 'LHipForce_z' 'LWaistForce_x' 'LWaistForce_y'
 'LWaistForce_z' 'RWaistForce_x' 'RWaistForce_y' 'RWaistForce_z'
 'LNeckForce_x' 'LNeckForce_y' 'LNeckForce_z' 'RNeckForce_x'
 'RNeckForce_y' 'RNeckForce_z' 'LShoulderForce_x' 'LShoulderForce_y'
 'LShoulderForce_z' 'RShoulderForce_x' 'RShoulderForce_y'
 'RShoulderForce_z' 'LElbowForce_x' 'LElbowForce_y' 'LElbowForce_z'
 'RElbowForce_x' 'RElbowForce_y' 'RElbowForce_z' 'LWristForce_x'
 'LWristForce_y' 'LWristForce_z' 'RWristForce_x' 'RWristForce_y'
 'RWristForce_z' 'RGroundReactionMoment_x' 'RGroundReactionMoment_y'
 'RGroundReactionMoment_z' 'LAnkleMoment_x' 'LAnkleMoment_y'
 'LAnkleMoment_z' 'RAnkleMoment_x' 'RAnkleMoment_y' 'RAnkleMoment_z'
 'RKneeMoment_x' 'RKneeMoment_y' 'RKneeMoment_z' 'LKneeMoment_x'
 'LKneeMoment_y' 'LKneeMoment_z' 'RHipMoment_x' 'RHipMoment_y'
 'RHipMoment_z' 'LHipMoment_x' 'LHipMoment_y' 'LHipMoment_z'
 'LWaistMoment_x' 'LWaistMoment_y' 'LWaistMoment_z' 'RWaistMoment_x'
 'RWaistMoment_y' 'RWaistMoment_z' 'LNeckMoment_x' 'LNeckMoment_y'
 'LNeckMoment_z' 'RNeckMoment_x' 'RNeckMoment_y' 'RNeckMoment_z'
 'LShoulderMoment_x' 'LShoulderMoment_y' 'LShoulderMoment_z'
 'RShoulderMoment_x' 'RShoulderMoment_y' 'RShoulderMoment_z'
 'LElbowMoment_x' 'LElbowMoment_y' 'LElbowMoment_z' 'RElbowMoment_x'
 'RElbowMoment_y' 'RElbowMoment_z' 'LWristMoment_x' 'LWristMoment_y'
 'LWristMoment_z' 'RWristMoment_x' 'RWristMoment_y' 'RWristMoment_z'
 'RTHI_x' 'RTHI_y' 'RTHI_z' 'CentreOfMass_x' 'CentreOfMass_y'
 'CentreOfMass_z' 'CentreOfMassFloor_x' 'CentreOfMassFloor_y'
 'CentreOfMassFloor_z' 'time']

In [10]:
fs_data

100.0

### Analogs

In [11]:
df_analogs

,Force.Fx1,Force.Fy1,Force.Fz1,Moment.Mx1,Moment.My1,Moment.Mz1,Force.Fx2,Force.Fy2,Force.Fz2,Moment.Mx2,...,Sensor 9 Acc.ACCX9,Sensor 9 Acc.ACCY9,Sensor 9 Acc.ACCZ9,Sensor 9 Gyro.GYROX9,Sensor 9 Gyro.GYROY9,Sensor 9 Gyro.GYROZ9,Sensor 9 Mag.MAGX9,Sensor 9 Mag.MAGY9,Sensor 9 Mag.MAGZ9,time
0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,3.473520,-4.494035,-8.726802,0.168759,0.086597,0.009415,0.0,0.0,0.0,0.0000
1,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,3.471404,-4.495009,-8.725497,0.169392,0.087099,0.009707,0.0,0.0,0.0,0.0005
2,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,3.469289,-4.495984,-8.724193,0.170026,0.087600,0.010000,0.0,0.0,0.0,0.0010
3,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,3.467173,-4.496959,-8.722888,0.170659,0.088101,0.010293,0.0,0.0,0.0,0.0015
4,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,3.465057,-4.497933,-8.721583,0.171292,0.088602,0.010585,0.0,0.0,0.0,0.0020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47095,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,3.136452,-6.965513,-6.846344,-0.806749,1.057827,0.421788,0.0,0.0,0.0,23.5475
47096,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,3.145909,-6.988296,-6.833465,-0.809163,1.057825,0.409830,0.0,0.0,0.0,23.5480
47097,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,3.155365,-7.011078,-6.820585,-0.811578,1.057823,0.397873,0.0,0.0,0.0,23.5485
47098,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,3.166712,-7.075538,-6.772002,-0.815389,1.057382,0.388196,0.0,0.0,0.0,23.5490
47099,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,3.178060,-7.139997,-6.723419,-0.819199,1.056941,0.378519,0.0,0.0,0.0,23.5495

In [12]:
# Pretty print list of columns in the analogs file
print(df_data.columns.values)

['PELO_x' 'PELO_y' 'PELO_z' 'PELA_x' 'PELA_y' 'PELA_z' 'PELL_x' 'PELL_y'
 'PELL_z' 'PELP_x' 'PELP_y' 'PELP_z' 'LFEO_x' 'LFEO_y' 'LFEO_z' 'LFEA_x'
 'LFEA_y' 'LFEA_z' 'LFEL_x' 'LFEL_y' 'LFEL_z' 'LFEP_x' 'LFEP_y' 'LFEP_z'
 'LTIO_x' 'LTIO_y' 'LTIO_z' 'LTIA_x' 'LTIA_y' 'LTIA_z' 'LTIL_x' 'LTIL_y'
 'LTIL_z' 'LTIP_x' 'LTIP_y' 'LTIP_z' 'LFOO_x' 'LFOO_y' 'LFOO_z' 'LFOA_x'
 'LFOA_y' 'LFOA_z' 'LFOL_x' 'LFOL_y' 'LFOL_z' 'LFOP_x' 'LFOP_y' 'LFOP_z'
 'RFEO_x' 'RFEO_y' 'RFEO_z' 'RFEA_x' 'RFEA_y' 'RFEA_z' 'RFEL_x' 'RFEL_y'
 'RFEL_z' 'RFEP_x' 'RFEP_y' 'RFEP_z' 'RTIO_x' 'RTIO_y' 'RTIO_z' 'RTIA_x'
 'RTIA_y' 'RTIA_z' 'RTIL_x' 'RTIL_y' 'RTIL_z' 'RTIP_x' 'RTIP_y' 'RTIP_z'
 'RFOO_x' 'RFOO_y' 'RFOO_z' 'RFOA_x' 'RFOA_y' 'RFOA_z' 'RFOL_x' 'RFOL_y'
 'RFOL_z' 'RFOP_x' 'RFOP_y' 'RFOP_z' 'LTOO_x' 'LTOO_y' 'LTOO_z' 'LTOA_x'
 'LTOA_y' 'LTOA_z' 'LTOL_x' 'LTOL_y' 'LTOL_z' 'LTOP_x' 'LTOP_y' 'LTOP_z'
 'RTOO_x' 'RTOO_y' 'RTOO_z' 'RTOA_x' 'RTOA_y' 'RTOA_z' 'RTOL_x' 'RTOL_y'
 'RTOL_z' 'RTOP_x' 'RTOP_y' 'RTOP_z' 'HEDO_x' 'HEDO_y' 'HEDO_z' 'HEDA_x'
 'HEDA_y' 'HEDA_z' 'HEDL_x' 'HEDL_y' 'HEDL_z' 'HEDP_x' 'HEDP_y' 'HEDP_z'
 'LCLO_x' 'LCLO_y' 'LCLO_z' 'LCLA_x' 'LCLA_y' 'LCLA_z' 'LCLL_x' 'LCLL_y'
 'LCLL_z' 'LCLP_x' 'LCLP_y' 'LCLP_z' 'RCLO_x' 'RCLO_y' 'RCLO_z' 'RCLA_x'
 'RCLA_y' 'RCLA_z' 'RCLL_x' 'RCLL_y' 'RCLL_z' 'RCLP_x' 'RCLP_y' 'RCLP_z'
 'TRXO_x' 'TRXO_y' 'TRXO_z' 'TRXA_x' 'TRXA_y' 'TRXA_z' 'TRXL_x' 'TRXL_y'
 'TRXL_z' 'TRXP_x' 'TRXP_y' 'TRXP_z' 'LHUO_x' 'LHUO_y' 'LHUO_z' 'LHUA_x'
 'LHUA_y' 'LHUA_z' 'LHUL_x' 'LHUL_y' 'LHUL_z' 'LHUP_x' 'LHUP_y' 'LHUP_z'
 'LRAO_x' 'LRAO_y' 'LRAO_z' 'LRAA_x' 'LRAA_y' 'LRAA_z' 'LRAL_x' 'LRAL_y'
 'LRAL_z' 'LRAP_x' 'LRAP_y' 'LRAP_z' 'LHNO_x' 'LHNO_y' 'LHNO_z' 'LHNA_x'
 'LHNA_y' 'LHNA_z' 'LHNL_x' 'LHNL_y' 'LHNL_z' 'LHNP_x' 'LHNP_y' 'LHNP_z'
 'RHUO_x' 'RHUO_y' 'RHUO_z' 'RHUA_x' 'RHUA_y' 'RHUA_z' 'RHUL_x' 'RHUL_y'
 'RHUL_z' 'RHUP_x' 'RHUP_y' 'RHUP_z' 'RRAO_x' 'RRAO_y' 'RRAO_z' 'RRAA_x'
 'RRAA_y' 'RRAA_z' 'RRAL_x' 'RRAL_y' 'RRAL_z' 'RRAP_x' 'RRAP_y' 'RRAP_z'
 'RHNO_x' 'RHNO_y' 'RHNO_z' 'RHNA_x' 'RHNA_y' 'RHNA_z' 'RHNL_x' 'RHNL_y'
 'RHNL_z' 'RHNP_x' 'RHNP_y' 'RHNP_z' 'RBHD_x' 'RBHD_y' 'RBHD_z' 'LSHO_x'
 'LSHO_y' 'LSHO_z' 'RSHO_x' 'RSHO_y' 'RSHO_z' 'RTIB_x' 'RTIB_y' 'RTIB_z'
 'T10_x' 'T10_y' 'T10_z' 'RWRB_x' 'RWRB_y' 'RWRB_z' 'RTOE_x' 'RTOE_y'
 'RTOE_z' 'LBHD_x' 'LBHD_y' 'LBHD_z' 'RANK_x' 'RANK_y' 'RANK_z' 'RMTF_x'
 'RMTF_y' 'RMTF_z' 'RFRM_x' 'RFRM_y' 'RFRM_z' 'RPSI_x' 'RPSI_y' 'RPSI_z'
 'RKNE_x' 'RKNE_y' 'RKNE_z' 'LMedANK_x' 'LMedANK_y' 'LMedANK_z' 'LPSI_x'
 'LPSI_y' 'LPSI_z' 'RTIP_NIM_x' 'RTIP_NIM_y' 'RTIP_NIM_z' 'RELB_x'
 'RELB_y' 'RELB_z' 'LFRM_x' 'LFRM_y' 'LFRM_z' 'RWRA_x' 'RWRA_y' 'RWRA_z'
 'LTIP_NIM_x' 'LTIP_NIM_y' 'LTIP_NIM_z' 'LMTF_x' 'LMTF_y' 'LMTF_z'
 'Addi_R_ULeg_x' 'Addi_R_ULeg_y' 'Addi_R_ULeg_z' 'LKNE_x' 'LKNE_y'
 'LKNE_z' 'RFIN_x' 'RFIN_y' 'RFIN_z' 'LFHD_x' 'LFHD_y' 'LFHD_z' 'LWRA_x'
 'LWRA_y' 'LWRA_z' 'LTHI_x' 'LTHI_y' 'LTHI_z' 'RMedANK_x' 'RMedANK_y'
 'RMedANK_z' 'RFHD_x' 'RFHD_y' 'RFHD_z' 'LELB_x' 'LELB_y' 'LELB_z'
 'LTRO_x' 'LTRO_y' 'LTRO_z' 'LWRB_x' 'LWRB_y' 'LWRB_z' 'RTRO_x' 'RTRO_y'
 'RTRO_z' 'LUPA_x' 'LUPA_y' 'LUPA_z' 'LTOE_x' 'LTOE_y' 'LTOE_z' 'LFIN_x'
 'LFIN_y' 'LFIN_z' 'Addi_L_ULeg_x' 'Addi_L_ULeg_y' 'Addi_L_ULeg_z'
 'LASI_x' 'LASI_y' 'LASI_z' 'RHEE_x' 'RHEE_y' 'RHEE_z' 'LTIB_x' 'LTIB_y'
 'LTIB_z' 'CLAV_x' 'CLAV_y' 'CLAV_z' 'RASI_x' 'RASI_y' 'RASI_z' 'LHEE_x'
 'LHEE_y' 'LHEE_z' 'STRN_x' 'STRN_y' 'STRN_z' 'LANK_x' 'LANK_y' 'LANK_z'
 'C7_x' 'C7_y' 'C7_z' 'RBAK_x' 'RBAK_y' 'RBAK_z' 'RUPA_x' 'RUPA_y'
 'RUPA_z' '*124_x' '*124_y' '*124_z' '*125_x' '*125_y' '*125_z' '*126_x'
 '*126_y' '*126_z' '*127_x' '*127_y' '*127_z' '*128_x' '*128_y' '*128_z'
 '*129_x' '*129_y' '*129_z' '*130_x' '*130_y' '*130_z' '*131_x' '*131_y'
 '*131_z' '*132_x' '*132_y' '*132_z' '*133_x' '*133_y' '*133_z' '*134_x'
 '*134_y' '*134_z' '*135_x' '*135_y' '*135_z' '*136_x' '*136_y' '*136_z'
 '*137_x' '*137_y' '*137_z' '*138_x' '*138_y' '*138_z' '*139_x' '*139_y'
 '*139_z' '*140_x' '*140_y' '*140_z' '*141_x' '*141_y' '*141_z' '*142_x'
 '*142_y' '*142_z' '*143_x' '*143_y' '*143_z' '*144_x' '*144_y' '*144_z'
 '*145_x' '*145_y' '*145_z' '*146_x' '*146_y' '*146_z' '*147_x' '*147_y'
 '*147_z' '*148_x' '*148_y' '*148_z' '*149_x' '*149_y' '*149_z' '*150_x'
 '*150_y' '*150_z' '*151_x' '*151_y' '*151_z' '*152_x' '*152_y' '*152_z'
 '*153_x' '*153_y' '*153_z' '*154_x' '*154_y' '*154_z' '*155_x' '*155_y'
 '*155_z' '*156_x' '*156_y' '*156_z' '*157_x' '*157_y' '*157_z' '*158_x'
 '*158_y' '*158_z' '*159_x' '*159_y' '*159_z' '*160_x' '*160_y' '*160_z'
 '*161_x' '*161_y' '*161_z' '*162_x' '*162_y' '*162_z' 'LHipAngles_x'
 'LHipAngles_y' 'LHipAngles_z' 'LKneeAngles_x' 'LKneeAngles_y'
 'LKneeAngles_z' 'LAbsAnkleAngle_x' 'LAbsAnkleAngle_y' 'LAbsAnkleAngle_z'
 'LAnkleAngles_x' 'LAnkleAngles_y' 'LAnkleAngles_z' 'RHipAngles_x'
 'RHipAngles_y' 'RHipAngles_z' 'RKneeAngles_x' 'RKneeAngles_y'
 'RKneeAngles_z' 'RAnkleAngles_x' 'RAnkleAngles_y' 'RAnkleAngles_z'
 'RAbsAnkleAngle_x' 'RAbsAnkleAngle_y' 'RAbsAnkleAngle_z'
 'LPelvisAngles_x' 'LPelvisAngles_y' 'LPelvisAngles_z' 'RPelvisAngles_x'
 'RPelvisAngles_y' 'RPelvisAngles_z' 'LFootProgressAngles_x'
 'LFootProgressAngles_y' 'LFootProgressAngles_z' 'RFootProgressAngles_x'
 'RFootProgressAngles_y' 'RFootProgressAngles_z' 'RNeckAngles_x'
 'RNeckAngles_y' 'RNeckAngles_z' 'LNeckAngles_x' 'LNeckAngles_y'
 'LNeckAngles_z' 'RSpineAngles_x' 'RSpineAngles_y' 'RSpineAngles_z'
 'LSpineAngles_x' 'LSpineAngles_y' 'LSpineAngles_z' 'LShoulderAngles_x'
 'LShoulderAngles_y' 'LShoulderAngles_z' 'LElbowAngles_x' 'LElbowAngles_y'
 'LElbowAngles_z' 'LWristAngles_x' 'LWristAngles_y' 'LWristAngles_z'
 'RShoulderAngles_x' 'RShoulderAngles_y' 'RShoulderAngles_z'
 'RElbowAngles_x' 'RElbowAngles_y' 'RElbowAngles_z' 'RWristAngles_x'
 'RWristAngles_y' 'RWristAngles_z' 'RThoraxAngles_x' 'RThoraxAngles_y'
 'RThoraxAngles_z' 'LThoraxAngles_x' 'LThoraxAngles_y' 'LThoraxAngles_z'
 'RHeadAngles_x' 'RHeadAngles_y' 'RHeadAngles_z' 'LHeadAngles_x'
 'LHeadAngles_y' 'LHeadAngles_z' 'LHipPower_x' 'LHipPower_y' 'LHipPower_z'
 'LKneePower_x' 'LKneePower_y' 'LKneePower_z' 'LAnklePower_x'
 'LAnklePower_y' 'LAnklePower_z' 'RHipPower_x' 'RHipPower_y' 'RHipPower_z'
 'RKneePower_x' 'RKneePower_y' 'RKneePower_z' 'RAnklePower_x'
 'RAnklePower_y' 'RAnklePower_z' 'LWaistPower_x' 'LWaistPower_y'
 'LWaistPower_z' 'RWaistPower_x' 'RWaistPower_y' 'RWaistPower_z'
 'LNeckPower_x' 'LNeckPower_y' 'LNeckPower_z' 'RNeckPower_x'
 'RNeckPower_y' 'RNeckPower_z' 'LShoulderPower_x' 'LShoulderPower_y'
 'LShoulderPower_z' 'RShoulderPower_x' 'RShoulderPower_y'
 'RShoulderPower_z' 'LElbowPower_x' 'LElbowPower_y' 'LElbowPower_z'
 'RElbowPower_x' 'RElbowPower_y' 'RElbowPower_z' 'LWristPower_x'
 'LWristPower_y' 'LWristPower_z' 'RWristPower_x' 'RWristPower_y'
 'RWristPower_z' 'RGroundReactionForce_x' 'RGroundReactionForce_y'
 'RGroundReactionForce_z' 'RNormalisedGRF_x' 'RNormalisedGRF_y'
 'RNormalisedGRF_z' 'LAnkleForce_x' 'LAnkleForce_y' 'LAnkleForce_z'
 'RAnkleForce_x' 'RAnkleForce_y' 'RAnkleForce_z' 'RKneeForce_x'
 'RKneeForce_y' 'RKneeForce_z' 'LKneeForce_x' 'LKneeForce_y'
 'LKneeForce_z' 'RHipForce_x' 'RHipForce_y' 'RHipForce_z' 'LHipForce_x'
 'LHipForce_y' 'LHipForce_z' 'LWaistForce_x' 'LWaistForce_y'
 'LWaistForce_z' 'RWaistForce_x' 'RWaistForce_y' 'RWaistForce_z'
 'LNeckForce_x' 'LNeckForce_y' 'LNeckForce_z' 'RNeckForce_x'
 'RNeckForce_y' 'RNeckForce_z' 'LShoulderForce_x' 'LShoulderForce_y'
 'LShoulderForce_z' 'RShoulderForce_x' 'RShoulderForce_y'
 'RShoulderForce_z' 'LElbowForce_x' 'LElbowForce_y' 'LElbowForce_z'
 'RElbowForce_x' 'RElbowForce_y' 'RElbowForce_z' 'LWristForce_x'
 'LWristForce_y' 'LWristForce_z' 'RWristForce_x' 'RWristForce_y'
 'RWristForce_z' 'RGroundReactionMoment_x' 'RGroundReactionMoment_y'
 'RGroundReactionMoment_z' 'LAnkleMoment_x' 'LAnkleMoment_y'
 'LAnkleMoment_z' 'RAnkleMoment_x' 'RAnkleMoment_y' 'RAnkleMoment_z'
 'RKneeMoment_x' 'RKneeMoment_y' 'RKneeMoment_z' 'LKneeMoment_x'
 'LKneeMoment_y' 'LKneeMoment_z' 'RHipMoment_x' 'RHipMoment_y'
 'RHipMoment_z' 'LHipMoment_x' 'LHipMoment_y' 'LHipMoment_z'
 'LWaistMoment_x' 'LWaistMoment_y' 'LWaistMoment_z' 'RWaistMoment_x'
 'RWaistMoment_y' 'RWaistMoment_z' 'LNeckMoment_x' 'LNeckMoment_y'
 'LNeckMoment_z' 'RNeckMoment_x' 'RNeckMoment_y' 'RNeckMoment_z'
 'LShoulderMoment_x' 'LShoulderMoment_y' 'LShoulderMoment_z'
 'RShoulderMoment_x' 'RShoulderMoment_y' 'RShoulderMoment_z'
 'LElbowMoment_x' 'LElbowMoment_y' 'LElbowMoment_z' 'RElbowMoment_x'
 'RElbowMoment_y' 'RElbowMoment_z' 'LWristMoment_x' 'LWristMoment_y'
 'LWristMoment_z' 'RWristMoment_x' 'RWristMoment_y' 'RWristMoment_z'
 'RTHI_x' 'RTHI_y' 'RTHI_z' 'CentreOfMass_x' 'CentreOfMass_y'
 'CentreOfMass_z' 'CentreOfMassFloor_x' 'CentreOfMassFloor_y'
 'CentreOfMassFloor_z' 'time']

In [13]:
fs_analog

2000.0